version: '3'
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    volumes:
      - ./create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=PasSwOrD
    restart: always
